Repository wizzie-io/normalizer, pull requests merged in 2018-12, with the labels that each got.

#36 WIZZIE-2998 Add DecimalPrecisionMapper function
  docker/build/Dockerfile
  docs/functions/mapper_functions.md
  functions/src/main/java/io/wizzie/normalizer/funcs/impl/DecimalPrecisionMapper.java
  service/src/test/java/io/wizzie/normalizer/funcs/impl/DecimalPrecisionMapperUnitTest.java
  service/src/test/resources/decimal-precision-mapper.json
Labels: feature

#38 WIZZIE-3104 & WIZZIE-3105 Add NumberComparingFilter function
  docs/functions/filter_functions.md
  functions/src/main/java/io/wizzie/normalizer/funcs/impl/NumberComparingFilter.java
  service/src/test/java/io/wizzie/normalizer/funcs/impl/NumberComparingFilterUnitTest.java
  service/src/test/resources/malformed-number-comparing-filter.json
  service/src/test/resources/number-comparing-filter.json
Labels: feature

#39 Fix seriealizer properties to support kafka 2.1.0
  docker/build/config_env.json
  service/src/main/java/io/wizzie/normalizer/builder/Builder.java
Labels: bug

#41 Fix readme links to docs
  README.md
Labels: documentation

#43 Fix stream monitor
  service/src/main/java/io/wizzie/normalizer/builder/StreamMonitor.java
Labels: bug

#46 Update readme content
  README.md
  docs/index.md
Labels: documentation

#45 Add logo print to normalizer
  service/src/main/java/io/wizzie/normalizer/Normalizer.java
  service/src/main/java/io/wizzie/normalizer/logo/LogoPrinter.java
Labels: improvement

#47 Add scalability docs
  README.md
  docs/_data/navigation.yml
  docs/architecture/scalability.md
  docs/index.md
Labels: documentation

#48 Fix TryToDoLoopException when send stream-plan two times
  service/src/main/java/io/wizzie/normalizer/builder/StreamBuilder.java
Labels: bug

#49 Fix deploy
  .circleci/config.yml
Labels: test

#50 Control all exceptions when load new stream-plan
  service/src/main/java/io/wizzie/normalizer/builder/Builder.java
Labels: bug

#51 Fix release deploy
  .circleci/config.yml
Labels: test
