Repository wizzie-io/normalizer, pull requests merged in 2018-10, with the labels that each got.

#13 Update metrics library to avoid memory leak
  pom.xml
  service/src/main/java/io/wizzie/normalizer/builder/Builder.java
Labels: bug

#15 Fix documentation typos
  docs/assets/images/compare_1.png
  docs/assets/images/compare_2.png
  docs/assets/images/dark-theme.png
  docs/assets/images/dashboard-locked.png
  docs/assets/images/dashboard-reload.png
  docs/assets/images/drill_down.png
  docs/assets/images/light-theme.png
  docs/assets/images/logo.png
  docs/assets/images/swagger-ui.png
  docs/assets/images/thresholds_1.png
  docs/assets/images/thresholds_2.png
  docs/assets/images/widgets/bar.png
  docs/assets/images/widgets/chord.png
  docs/assets/images/widgets/heatmap.png
  docs/assets/images/widgets/location.png
  docs/assets/images/widgets/multiserie.png
  docs/assets/images/widgets/pie.png
  docs/assets/images/widgets/plane.png
  docs/assets/images/widgets/plane_location.png
  docs/assets/images/widgets/plane_route.png
  docs/assets/images/widgets/route.png
  docs/assets/images/widgets/sankey.png
  docs/assets/images/widgets/serie_area.png
  docs/assets/images/widgets/serie_bar.png
  docs/assets/images/widgets/serie_line.png
  docs/assets/images/widgets/table.png
  docs/assets/images/widgets/value_1.png
  docs/assets/images/widgets/value_2.png
  docs/functions/mapper_functions.md
  docs/functions/store_mapper_functions.md
  docs/index.md
Labels: bug

#16 Update FieldFilter function to support null as filtered value
  functions/src/main/java/io/wizzie/normalizer/funcs/impl/FieldFilter.java
  service/src/test/java/io/wizzie/normalizer/funcs/impl/FieldFilterUnitTest.java
  service/src/test/resources/field-filter.json
Labels: improvement

#18 WIZZIE-2720 Update normalizer jackson-databind
  functions/pom.xml
  model/pom.xml
  pom.xml
  service/pom.xml
Labels: bug

#19 Add env variables to allow file bootstraper
  docker/build/Dockerfile
  docker/build/config_env.json
Labels: improvement

#22 WIZZIE-2810 Update config bootstrapper & metrics library at normalizer
  pom.xml
Labels: bug

#23 WIZZIE-2783 Add capability to create not-reversible loops between/to streams
  docs/_data/navigation.yml
  docs/architecture/topology_path.md
  docs/assets/images/architecture/not-allowed-topology-path.png
  docs/assets/images/architecture/simple-topology.png
  docs/assets/images/architecture/topology-path-1.png
  docs/assets/images/architecture/topology-path-2.png
  service/src/main/java/io/wizzie/normalizer/builder/StreamBuilder.java
  service/src/test/java/io/wizzie/normalizer/StreamBuilderTest.java
  service/src/test/java/io/wizzie/normalizer/integration/SendToStreamInOtherIterationIntegrationTest.java
  service/src/test/java/io/wizzie/normalizer/integration/SendToStreamInSameIterationIntegrationTest.java
  service/src/test/resources/loop-stream.json
  service/src/test/resources/loop-to-previous-stream.json
  service/src/test/resources/loop-to-same-stream-in-same-iteration.json
  service/src/test/resources/loop-to-stream-in-other-iteration.json
  service/src/test/resources/loop-to-stream-in-same-iteration.json
Labels: documentation, improvement
