Repository wizzie-io/normalizer, pull requests merged in 2018-11, with the labels that each got.

#24 WIZZIE-2789 Add sinks model validator
  model/src/main/java/io/wizzie/normalizer/model/PlanModel.java
  service/src/test/java/io/wizzie/normalizer/model/PlanModelUnitTest.java
  service/src/test/resources/filter-not-null.json
Labels: bug

#27 Fix tutorial links.
  README.md
Labels: documentation

#25 Fix typo bootstraper->bootstrapper
  base/src/main/java/io/wizzie/normalizer/base/builder/config/ConfigProperties.java
  config/sample_config.json
  docker/build/config_env.json
  docs/configuration/multi_tenant.md
  docs/getting_started/base_tutorial.md
  pom.xml
  service/src/main/java/io/wizzie/normalizer/base/utils/bootstrap/StreamerKafkaConfig.java
  service/src/main/java/io/wizzie/normalizer/builder/Builder.java
  service/src/test/java/io/wizzie/normalizer/integration/FileBootstrapperIntegrationTest.java
  service/src/test/java/io/wizzie/normalizer/integration/KafkaBootstrapperChangeConfigIntegrationTest.java
  service/src/test/java/io/wizzie/normalizer/integration/KafkaBootstrapperGetConfigIntegrationTest.java
  service/src/test/java/io/wizzie/normalizer/integration/KafkaBootstrapperIntegrationTest.java
  service/src/test/java/io/wizzie/normalizer/integration/KafkaMetricListenerIntegrationTest.java
  service/src/test/java/io/wizzie/normalizer/integration/MultiIdIntegrationTest.java
  service/src/test/resources/kafka-bootstrapper-integration-test-1.json
  service/src/test/resources/kafka-bootstrapper-integration-test-2.json
Labels: bug

#28 Fix loop between streams in same iteration
  service/src/main/java/io/wizzie/normalizer/builder/StreamBuilder.java
  service/src/test/java/io/wizzie/normalizer/StreamBuilderTest.java
  service/src/test/resources/loop-between-streams-in-same-iteration.json
Labels: bug

#30 Fix normalizer-start.sh output log4j2.xml file
  docker/build/normalizer-start.sh
Labels: bug

#31 WIZZIE-2990 Fix delimitier typo
  docs/functions/mapper_functions.md
  functions/src/main/java/io/wizzie/normalizer/funcs/impl/JoinMapper.java
  functions/src/main/java/io/wizzie/normalizer/funcs/impl/StringSplitterMapper.java
  service/src/test/java/io/wizzie/normalizer/funcs/impl/JoinMapperUnitTest.java
  service/src/test/java/io/wizzie/normalizer/funcs/impl/StringSplitterMapperUnitTest.java
  service/src/test/resources/join-mapper.json
  service/src/test/resources/string-splitter-mapper.json
Labels: bug

#29 Support Double and Float at ConversionUtils
  base/src/main/java/io/wizzie/normalizer/base/utils/ConversionUtils.java
  service/src/test/java/io/wizzie/normalizer/base/utils/ConversionUtilsUnitTest.java
Labels: improvement

#32 WIZZIE-2992 Add support to create stream from multiple topics
  docs/configuration/stream_configuration.md
  model/src/main/java/io/wizzie/normalizer/model/PlanModel.java
  service/src/main/java/io/wizzie/normalizer/builder/StreamBuilder.java
  service/src/test/java/io/wizzie/normalizer/integration/StreamFromMultipleInputTopicsIntegrationTest.java
  service/src/test/resources/stream-from-multiple-topics-integration.json
Labels: feature

#33 WIZZIE-2983 Move __MATCH filter inside filters instead of Kafka Stream building
  functions/src/main/java/io/wizzie/normalizer/funcs/FilterFunc.java
  functions/src/main/java/io/wizzie/normalizer/funcs/impl/AndFilter.java
  functions/src/main/java/io/wizzie/normalizer/funcs/impl/OrFilter.java
  service/src/main/java/io/wizzie/normalizer/builder/StreamBuilder.java
Labels: improvement

#35 Update to kafka 2.1.0
  functions/src/main/java/io/wizzie/normalizer/funcs/MapperStoreFunction.java
  pom.xml
  service/src/main/java/io/wizzie/normalizer/builder/Builder.java
  service/src/test/java/io/wizzie/normalizer/mocks/MockProcessContext.java
Labels: improvement
