Repository wizzie-io/normalizer, pull requests merged in 2018-07, with the labels that each got.

#1 WIZZIE-2185 Update normalizer to Kafka 1.1.0
  base/pom.xml
  functions/pom.xml
  model/pom.xml
  pom.xml
  service/pom.xml
Labels: improvement

#2 WIZZIE-2251 Increase config-bootstrapper and metrics version at normalizer
  pom.xml
Labels: feature

#6 WIZZIE-2295 Prepare pom.xml to deploy to maven central repo
  .circleci/config.yml
  .circleci/maven-settings.xml
  docker/pom.xml
  service/pom.xml
Labels: improvement, test

#5 WIZZIE-2305 Develop normalizer group regex function
  docs/_posts/2017-02-14-mapper-functions.md
  functions/src/main/java/io/wizzie/normalizer/funcs/impl/RegexMapper.java
  service/src/test/java/io/wizzie/normalizer/funcs/impl/RegexMapperUnitTest.java
  service/src/test/resources/regex-mapper.json
Labels: feature

#4 WIZZIE-2296 Review normalizer documentation
  .circleci/config.yml
  docker/build/Dockerfile
  docs/_posts/2017-02-14-custom-functions.md
  docs/_posts/2017-02-14-definition-boostrapper.md
  docs/_posts/2017-02-14-topics.md
  docs/_posts/2017-02-17-custom-development.md
  docs/_posts/2017-08-17-docker-intro.md
  docs/index.md
Labels: documentation

#7 Fix tagged deploy at circle config.yml
  .circleci/config.yml
Labels: improvement, test
